#!/bin/sh
set -eu
set +x

env_file=${1:-.env.test}
if [ ! -f "$env_file" ]; then
  echo "Missing test environment file: $env_file" >&2
  exit 1
fi

# The file is generated by init-test-env.sh and contains simple KEY=value pairs.
# shellcheck disable=SC1090
. "./$env_file"

: "${APP_PUBLIC_BASE_URL:?APP_PUBLIC_BASE_URL is required}"
: "${TELEGRAM_CLIENT_BOT_TOKEN:?TELEGRAM_CLIENT_BOT_TOKEN is required}"
: "${TELEGRAM_WEBHOOK_SECRET:?TELEGRAM_WEBHOOK_SECRET is required}"

response=$(curl --fail --silent --show-error \
  --request POST \
  --data-urlencode "url=${APP_PUBLIC_BASE_URL}/api/v1/telegram/client/webhook" \
  --data-urlencode "secret_token=${TELEGRAM_WEBHOOK_SECRET}" \
  "https://api.telegram.org/bot${TELEGRAM_CLIENT_BOT_TOKEN}/setWebhook")

case "$response" in
  *'"ok":true'*)
    echo "Test Telegram webhook configured."
    ;;
  *)
    echo "Telegram rejected the test webhook configuration." >&2
    exit 1
    ;;
esac

menu_button=$(printf '{"type":"web_app","text":"Open test","web_app":{"url":"%s"}}' "$TELEGRAM_CLIENT_MINI_APP_URL")
response=$(curl --fail --silent --show-error \
  --request POST \
  --data-urlencode "menu_button=${menu_button}" \
  "https://api.telegram.org/bot${TELEGRAM_CLIENT_BOT_TOKEN}/setChatMenuButton")

case "$response" in
  *'"ok":true'*)
    echo "Test bot Mini App menu button configured."
    ;;
  *)
    echo "Telegram rejected the test Mini App menu button." >&2
    exit 1
    ;;
esac
