#!/bin/sh
set -eu
set +x

umask 077

: "${TEST_BASE_URL:?TEST_BASE_URL is required}"
: "${TEST_BOT_USERNAME:?TEST_BOT_USERNAME is required}"
: "${TEST_DEPLOY_PATH:?TEST_DEPLOY_PATH is required}"

IFS= read -r test_bot_token
case "$test_bot_token" in
  [0-9]*:[A-Za-z0-9_-]*) ;;
  *)
    echo "Invalid Telegram bot token format." >&2
    exit 1
    ;;
esac

env_file=.env.test
if [ -f "$env_file" ]; then
  # This file is generated by this script and contains only simple KEY=value pairs.
  # shellcheck disable=SC1090
  . "./$env_file"
fi

random_secret() {
  openssl rand -base64 48 | tr -d '\r\n'
}

app_encryption_key=${APP_ENCRYPTION_KEY:-$(random_secret)}
pii_hash_key=${PII_HASH_KEY:-$(random_secret)}
postgres_password=${POSTGRES_PASSWORD:-$(random_secret)}
telegram_webhook_secret=${TELEGRAM_WEBHOOK_SECRET:-$(random_secret)}

if [ "$app_encryption_key" = "$pii_hash_key" ]; then
  pii_hash_key=$(random_secret)
fi

tmp_file="${env_file}.tmp"
cat > "$tmp_file" <<EOF
APP_ENV=production
APP_BUILD_SHA=unknown
HTTP_ADDR=:8080
APP_TIMEZONE=Europe/Belgrade
APP_CURRENCY=RSD
APP_PUBLIC_BASE_URL=$TEST_BASE_URL
APP_ALLOWED_ORIGINS=$TEST_BASE_URL
APP_ENCRYPTION_KEY=$app_encryption_key
PII_HASH_KEY=$pii_hash_key
POSTGRES_PASSWORD=$postgres_password
TELEGRAM_WEBHOOK_SECRET=$telegram_webhook_secret
TELEGRAM_CLIENT_BOT_USERNAME=$TEST_BOT_USERNAME
TELEGRAM_CLIENT_BOT_TOKEN=$test_bot_token
TELEGRAM_CLIENT_MINI_APP_URL=$TEST_BASE_URL/main/
TELEGRAM_STAFF_BOT_USERNAME=
TELEGRAM_STAFF_BOT_TOKEN=
BOOTSTRAP_OWNER_TELEGRAM_IDS=1048084234,8241921060,8609105840,7604602332
BOOTSTRAP_OWNER_TELEGRAM_ID=1048084234
LOCAL_ROLE_SWITCHER_ENABLED=false
POSTGRES_MAX_CONNS=8
POSTGRES_MIN_CONNS=1
POSTGRES_MAX_CONN_IDLE_TIME=5m
SESSION_TTL=24h
TELEGRAM_INIT_DATA_MAX_AGE=24h
MAX_ITEM_QUANTITY=99
NOTIFICATION_DRY_RUN=false
NOTIFICATION_POLL_INTERVAL=5s
NOTIFICATION_CONCURRENCY=4
NOTIFICATION_BACKLOG_ALERT_AFTER=60s
SERVER_TIMING_ENABLED=false
PII_RETENTION_DAYS=730
FISCAL_PROCESS_ACCEPTED=false
APP_HOST_PORT=18081
MEDIA_VOLUME_HOST_PATH=/srv/tk-delivery-test/uploads
EOF
chmod 600 "$tmp_file"
mv "$tmp_file" "$env_file"
install -d -m 750 /srv/tk-delivery-test/uploads
